### ISSUE TITLE
Messages' tag parsing is handled by locally catching errors

### ISSUE THREAD

**Issue by Supinic** [robotty/dank-twitch-irc#25]
When parsing message tags, methods that parse specific tag types rely on locally caught errors to determine whether or not given tags are present in the message.

This leads to performance drops as constructing an `Error` object (in this case, `ParseError` or `MissingTagError`), throwing and then locally catching it is not trivial in the backend - compared to, for instance, returning a null value.

Attached is a CPU profilling snippet preview, where this behaviour is shown. In a single message event, almost 60-70% of processing is done in local error catching.

![dank_twitch_local_error](https://user-images.githubusercontent.com/7684273/68845605-f6fb1800-06cb-11ea-8c4a-d85534d273af.png)

**Comment by RAnders00** [comment]
I will try out babel and optional chaining

**Comment by Supinic** [comment]
Changes seem good. On average, each messages's handling time has gone down by ~50% on my setup.

Attached is a snippet of CPU profile, no more errors are being thrown and overall the performance is faster. Red rectangle signifies a custom listener to the `message` emitter.

![image](https://user-images.githubusercontent.com/7684273/68865028-6683fe00-06f2-11ea-9bc5-b03bba7c5c5a.png)
