### ISSUE TITLE
Change color.

### ISSUE THREAD

**Issue by sparkaccounts** [robotty/dank-twitch-irc#27]
There isn't a function to change the username color. So I wanted to see if anyone knows the IRC sendRaw to do this?

**Comment by RAnders00** [comment]
From Twitch, /color command:

> Usage: "/color <color>" - Change your username color. Color must be in hex (#000000) or one of the following: Blue, BlueViolet, CadetBlue, Chocolate, Coral, DodgerBlue, Firebrick, GoldenRod, Green, HotPink, OrangeRed, Red, SeaGreen, SpringGreen, YellowGreen. 

You can execute the /color command like this:

```javascript
let hexCode = "#AABBCC";
client.privmsg(client.configuration.username, "/color ${hexCode}")
```

**Comment by sparkaccounts** [comment]
Okay. Thanks. Although you should add a function to do this easier.

**Comment by RAnders00** [comment]
I will leave it open to track adding that specific function.
