### ISSUE TITLE
Local error catching in parseTwitchMessage

### ISSUE THREAD

**Issue by Supinic** [robotty/dank-twitch-irc#29]
Similar to #25, parsing string tags in `parseTwitchMessage` (specifically when parsing `ClearchatMessage`) is done by locally catching and throwing errors. This has a signifcant impact on performance, especially when multiple are being encountered at the same time.

![image](https://user-images.githubusercontent.com/7684273/76899675-547cbc80-6898-11ea-9365-4bf2bc8bf5a9.png)

**Comment by RAnders00** [comment]
I think you have an outdated version. Those methods were removed when #25 was fixed, which has been released with version 3.0.4.
