### ISSUE TITLE
Non ES2018 support

### ISSUE THREAD

**Issue by gempir** [robotty/dank-twitch-irc#30]
When running dank-twitch-irc in a browser that has no ES2018 support (like Firefox) it will crash because of some regexp issue. 

It would be nice if dank-twitch-irc supported most major browsers and recent versions of them.

**Comment by gempir** [comment]
8896b8be1cc374510dc98c462044ef5b3abbb28e fixed it and it's now in 3.2.6

**Comment by gempir** [comment]
You need to initialize it with websocket configuration option https://github.com/gempir/raftchat/blob/master/src/state/Store.tsx#L19

```
new ChatClient({
			connection: {
				type: "websocket",
				secure: true,
			}
		})
```

**Comment by KaKi87** [comment]
I mean, `ChatClient` is undefined in the first place 😅

**Comment by gempir** [comment]
You need a bundler and then import it. 

`import { ChatClient } from "dank-twitch-irc";`

**Comment by KaKi87** [comment]
You mean I can't do it without webpack ? :/

**Comment by KaKi87** [comment]
I can't do it in vanilla JS, for a userscript ?

**Comment by gempir** [comment]
By default this library isn't compatible in that way I think, so no. Needs to be some sort of module thingy not 100% sure, I always use a bundler

**Comment by RAnders00** [comment]
Yes, this library wasn't originally meant to run natively in the browser. However with the websocket configuration option you can make it work, if you use a bundler like webpack or parcel.
