### ISSUE TITLE
random fails when trying to send a message

### ISSUE THREAD

**Issue by Enji0** [robotty/dank-twitch-irc#302]
dank-twitch-irc randomly fails when trying to send a message with this error:
`SayError: Failed to say [#channel]: message: Timed out after waiting for response for 2000 milliseconds`

**Comment by RAnders00** [comment]
does the message actually end up being sent to that twitch channel, i.e. can you see the bot posting the message when watching twitch chat?

**Comment by Enji0** [comment]
No, the message don't end up being sent to the twitch channel.
btw, I'm using `await client.say(channel, message)`

**Comment by RAnders00** [comment]
Then the error message is right of course, it informs you that the message could not be delivered.

**Comment by Enji0** [comment]
I still sometimes get this error when I'm not using await
