### ISSUE TITLE
Allow sending messages with preceding "#" in channel name

### ISSUE THREAD

**Issue by 5E7EN** [robotty/dank-twitch-irc#31]
### Feature request

Invocation of the `<ChatClient>.say()` method when "#" is included at the beginning of the channel name currently results in a `ValidationError: Channel name "#channel" is invalid/malformed` error.

<hr>

As someone porting over from another IRC library which allows such behavior, my code is written in such a way so that messages must be able to send with the preceding "#" before the channel name. Perhaps it would be worthwhile to implement such functionality as well?

**Comment by RAnders00** [comment]
Do you also want messages to have the `#` character in the channel field?

**Comment by 5E7EN** [comment]
I suppose a config option to allow `#` while sending messages, as well as what you mentioned, would be neat. 👍
