### ISSUE TITLE
Some eventParams are inaccurate in the readme

### ISSUE THREAD

**Issue by johnpyp** [robotty/dank-twitch-irc#34]
It seems twitch has, at some point, changed the labels for some of their USERNOTICE eventParams such that they're inaccurate right now in the readme. I'm not sure what the correct solution for this is long term, since twitch is willing to just switch everything up willy nilly, but here's a few I noticed:

`subgift`:
- `recipientUsername` is actually `recipientUserName`
- There's a `giftMonths` param, not sure what this does.
- There's also an `originID` param, not sure what this does.

`raid`:
- `displayName` -> `displayname`
- `viewerCount` -> `viewercount`, and it comes in as a string.
- There's a `profileimageurl` param

**Comment by KararTY** [comment]
Have you tried out the values? As in, do the values still work and return the correct value?

It seems some of those are intentional, for users who use the library:
https://github.com/robotty/dank-twitch-irc/blob/master/CHANGELOG.md#v300

**Comment by johnpyp** [comment]
I noticed this issue because the documented values were actually undefined, so I started logging the eventParams. I should've clarified more, above I'm talking about what the "expected" params would be, based on the readme, compared to what I actually found there was when logging the eventParams. Since the eventParams are dynamically constructed from the irc message, I'd guess there was an api change at some point.

**Comment by KararTY** [comment]
You're right, I've just tried it out and `anonsubgift` & `subgift` `recipientUsername` returns `undefined`.

`recipientUserName` returns username properly as you've reported.

Here's an example eventParams for `subgift`:
```js
{
  giftMonths: '1',
  months: 1,
  monthsRaw: '1',
  originID: 'da 39 a3 ee 5e 6b 4b 0d 32 55 bf ef 95 60 18 90 af d8 07 09',
  recipientDisplayName: 'Skin_Spy',
  recipientID: '155340072',
  recipientUserName: 'skin_spy',
  senderCount: '0',
  subPlanName: 'Channel Subscription (asmongold)',
  subPlan: '1000'
}
```

**Comment by RAnders00** [comment]
I will fix this shortly

**Comment by RAnders00** [comment]
the undocumented parameters you are seeing are things Twitch don't document. The library parses all `msg-param-` parameters, camelcases the names, and puts them into an object. I just fixed the incorrect camelcasing of userName -> username
