### ISSUE TITLE
Question: Clarification on Guidance for JOIN/PART events

### ISSUE THREAD

**Issue by clarkio** [robotty/dank-twitch-irc#41]
In the [Client Options](https://github.com/robotty/dank-twitch-irc/blob/master/README.md#client-options) documentation and  specifically for the `requestMembershipCapability` option it mentions the following:

```
  // If you need live update of who's joining and leaving chat,
  // poll the tmi.twitch.tv chatters endpoint instead since it
  // is also more reliable
```

I've searched high and low in the Twitch documentation for a "chatters" endpoint. Could you please share what you mean by that? Is it an API endpoint or a hidden IRC command?

I'm trying to get close to real-time capture of JOIN/PART events but it seems most libraries are delayed in receiving these events by about three minutes. Is it possible to capture these faster?

Thanks in advance for any advice/guidance you have to offer 🙂👍

**Comment by Supinic** [comment]
What you mention about `JOIN` and `PART` events seems to be by Twitch's specification, i.e. you don't receive the events in real time. Moreover, the events aren't sent at all if the chatroom exceeds ~1000 chatters.
The TMI chatters endpoint is `/group/user/<channel>/chatters`. See [this discussion](https://discuss.dev.twitch.tv/t/irc-join-part-events-delayed-significantly/15519/5) for more info.

**Comment by RAnders00** [comment]
@clarkio there is no way of getting when users join a chat in real-time. The fastest option you have is to repeatedly poll the endpoint @Supinic linked above. Using that endpoint, you will probably be able to received changes faster than the three minutes delay you were getting from IRC libraries.

**Comment by clarkio** [comment]
Thank you both for your help and pointing me in the right direction @Supinic @RAnders00. That is interesting that the events are no longer sent for chatrooms exceeding 1000 chatters. Appreciate the heads up on that as well.
